version: '3.8'

volumes:
  postgres-data:
  node_modules:


services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=acronym_dev
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/flask-app
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/ember-app
      - .bash_history:/root/.bash_history
      - node_modules:/ember-app/node_modules
    tmpfs:
      - /ember-app/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
    depends_on:
      - backend
