version: "3.8"

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=acronym_dev
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/flask-app
    restart: unless-stopped
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/ember-app
      - /ember-app/node_modules
    tmpfs:
      - /ember-app/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
    restart: unless-stopped
    depends_on:
      - backend
