version: "3.8"

volumes:
  postgres-data:
  exclude:

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=acronym_dev
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5431:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  postgres-test:
    image: postgres
    environment:
      - POSTGRES_USER=acronym_test
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5430:5432
  backend:
    environment:
      WAIT_HOSTS: postgres:5432
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/flask-app
    restart: unless-stopped
    depends_on:
      - postgres
  frontend:
    environment:
      WAIT_HOSTS: backend:5000
    build:
      context: ./frontend
    volumes:
      - ./frontend:/ember-app
      - exclude:/ember-app/node_modules
    tmpfs:
      - /ember-app/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
    restart: unless-stopped
    depends_on:
      - backend
