"""empty message

Revision ID: a76b4120a840
Revises: 0abfbfff8217
Create Date: 2022-07-20 17:20:47.885948

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a76b4120a840"
down_revision = "0abfbfff8217"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("acronym", sa.Column("created", sa.DateTime(), nullable=True))
    op.drop_column("acronym", "created_when")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "acronym",
        sa.Column(
            "created_when", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("acronym", "created")
    # ### end Alembic commands ###
