"""empty message

Revision ID: c13ced84655c
Revises: a76b4120a840
Create Date: 2022-07-21 19:21:07.363561

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c13ced84655c"
down_revision = "a76b4120a840"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("acronym", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column(
        "acronym", sa.Column("last_modified_at", sa.DateTime(), nullable=True)
    )
    op.drop_column("acronym", "created")
    op.drop_column("acronym", "last_modified")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "acronym",
        sa.Column(
            "last_modified", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "acronym",
        sa.Column(
            "created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("acronym", "last_modified_at")
    op.drop_column("acronym", "created_at")
    # ### end Alembic commands ###
